2022-08-13 13:52:11,076 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 13:53:15,825 - INFO - µ±Ç°Ä¸½ø³Ì: 17228
2022-08-13 13:53:15,861 - INFO - 127.0.0.1 - - [13/Aug/2022 13:53:15] "[35m[1mGET /api/basics HTTP/1.1[0m" 500 -
2022-08-13 13:53:15,946 - INFO - 127.0.0.1 - - [13/Aug/2022 13:53:15] "[35m[1mPOST /api/basics HTTP/1.1[0m" 500 -
2022-08-13 13:57:02,138 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 9188 and this is thread id 16344.
2022-08-13 13:57:02,140 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000002552FD34740>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 9188 and this is thread id 16344.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 9188 and this is thread id 16344.
2022-08-13 13:57:07,985 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 13:57:18,720 - INFO - µ±Ç°Ä¸½ø³Ì: 16728
2022-08-13 13:57:18,756 - INFO - 127.0.0.1 - - [13/Aug/2022 13:57:18] "[35m[1mGET /api/basics HTTP/1.1[0m" 500 -
2022-08-13 13:57:18,828 - INFO - 127.0.0.1 - - [13/Aug/2022 13:57:18] "[35m[1mPOST /api/basics HTTP/1.1[0m" 500 -
2022-08-13 13:59:00,623 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 12348 and this is thread id 13728.
2022-08-13 13:59:00,626 - ERROR - Exception closing connection <sqlite3.Connection object at 0x0000025607E48640>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 12348 and this is thread id 13728.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 12348 and this is thread id 13728.
2022-08-13 13:59:03,123 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 13:59:11,634 - INFO - µ±Ç°Ä¸½ø³Ì: 7864
2022-08-13 13:59:11,665 - INFO - 127.0.0.1 - - [13/Aug/2022 13:59:11] "[35m[1mGET /api/basics HTTP/1.1[0m" 500 -
2022-08-13 13:59:12,550 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 13:59:12,551 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/0e196f4a-1acd-11ed-9d22-a0510bad1688.key
2022-08-13 13:59:12,552 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 13:59:21,620 - INFO - {"address":"14n6feKHiWLkYyuwW8ig7QAYE9Y8tFzWYNYvf79Ai33QmAp9VcM","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 13:59:21,956 - INFO - ´´½¨³É¹¦
2022-08-13 13:59:21,971 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 13:59:21,971 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/13b6b1b5-1acd-11ed-afbf-a0510bad1688.key
2022-08-13 13:59:21,971 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 13:59:29,765 - INFO - {"address":"13M4tVhdKxvPoXzv5ihC3Xg4n4EoM9kk9jaJpHeR5w82AUUViiM","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 13:59:30,109 - INFO - ´´½¨³É¹¦
2022-08-13 13:59:30,134 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 13:59:30,134 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/18945ff6-1acd-11ed-a60f-a0510bad1688.key
2022-08-13 13:59:30,135 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 13:59:37,861 - INFO - {"address":"14TGU4XGmQMbLqRz5G3a3c9Eip6WXnxYJHqzfxWnwuRsu8AMVb7","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 13:59:38,182 - INFO - ´´½¨³É¹¦
2022-08-13 13:59:38,387 - INFO - 127.0.0.1 - - [13/Aug/2022 13:59:38] "POST /api/basics HTTP/1.1" 200 -
2022-08-13 14:00:06,871 - INFO - 127.0.0.1 - - [13/Aug/2022 14:00:06] "[33mGET /wallet HTTP/1.1[0m" 404 -
2022-08-13 14:00:07,297 - INFO - 127.0.0.1 - - [13/Aug/2022 14:00:07] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 14:00:13,407 - INFO - 127.0.0.1 - - [13/Aug/2022 14:00:13] "GET / HTTP/1.1" 200 -
2022-08-13 14:00:13,469 - INFO - 127.0.0.1 - - [13/Aug/2022 14:00:13] "[36mGET /js/chunk-vendors.79915abe.js HTTP/1.1[0m" 304 -
2022-08-13 14:00:13,471 - INFO - 127.0.0.1 - - [13/Aug/2022 14:00:13] "[36mGET /css/chunk-vendors.0b0c58b7.css HTTP/1.1[0m" 304 -
2022-08-13 14:00:13,472 - INFO - 127.0.0.1 - - [13/Aug/2022 14:00:13] "[36mGET /css/app.61a069f3.css HTTP/1.1[0m" 304 -
2022-08-13 14:00:13,488 - INFO - 127.0.0.1 - - [13/Aug/2022 14:00:13] "[36mGET /js/app.19c66b8a.js HTTP/1.1[0m" 304 -
2022-08-13 14:00:13,818 - INFO - 127.0.0.1 - - [13/Aug/2022 14:00:13] "GET /js/chunk-vendors.79915abe.js.map HTTP/1.1" 200 -
2022-08-13 14:00:13,819 - INFO - 127.0.0.1 - - [13/Aug/2022 14:00:13] "GET /js/app.19c66b8a.js.map HTTP/1.1" 200 -
2022-08-13 14:00:13,847 - INFO - 127.0.0.1 - - [13/Aug/2022 14:00:13] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 14:00:13,857 - INFO - 127.0.0.1 - - [13/Aug/2022 14:00:13] "[35m[1mGET /api/basics HTTP/1.1[0m" 500 -
2022-08-13 14:00:13,867 - INFO - 127.0.0.1 - - [13/Aug/2022 14:00:13] "[36mGET /fonts/element-icons.ff18efd1.woff HTTP/1.1[0m" 304 -
2022-08-13 14:06:28,681 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1016 and this is thread id 8176.
2022-08-13 14:06:28,683 - ERROR - Exception closing connection <sqlite3.Connection object at 0x00000278704B5740>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1016 and this is thread id 8176.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1016 and this is thread id 8176.
2022-08-13 14:06:28,684 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 9488 and this is thread id 8176.
2022-08-13 14:06:28,684 - ERROR - Exception closing connection <sqlite3.Connection object at 0x00000278704B4740>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 9488 and this is thread id 8176.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 9488 and this is thread id 8176.
2022-08-13 14:06:30,983 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 14:06:37,494 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:37] "[33mGET /wallet HTTP/1.1[0m" 404 -
2022-08-13 14:06:37,913 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:37] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 14:06:41,913 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:41] "GET / HTTP/1.1" 200 -
2022-08-13 14:06:41,970 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:41] "[36mGET /js/chunk-vendors.79915abe.js HTTP/1.1[0m" 304 -
2022-08-13 14:06:41,971 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:41] "[36mGET /css/chunk-vendors.0b0c58b7.css HTTP/1.1[0m" 304 -
2022-08-13 14:06:41,972 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:41] "[36mGET /css/app.61a069f3.css HTTP/1.1[0m" 304 -
2022-08-13 14:06:41,977 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:41] "[36mGET /js/app.19c66b8a.js HTTP/1.1[0m" 304 -
2022-08-13 14:06:42,295 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:42] "GET /js/chunk-vendors.79915abe.js.map HTTP/1.1" 200 -
2022-08-13 14:06:42,296 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:42] "GET /js/app.19c66b8a.js.map HTTP/1.1" 200 -
2022-08-13 14:06:42,304 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:42] "[36mGET /fonts/element-icons.ff18efd1.woff HTTP/1.1[0m" 304 -
2022-08-13 14:06:42,322 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:42] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 14:06:42,323 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:42] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:06:50,275 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:50] "[33mGET /wallet HTTP/1.1[0m" 404 -
2022-08-13 14:06:50,677 - INFO - 127.0.0.1 - - [13/Aug/2022 14:06:50] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 14:07:14,030 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:14] "GET / HTTP/1.1" 200 -
2022-08-13 14:07:14,106 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:14] "[36mGET /js/chunk-vendors.79915abe.js HTTP/1.1[0m" 304 -
2022-08-13 14:07:14,107 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:14] "[36mGET /css/chunk-vendors.0b0c58b7.css HTTP/1.1[0m" 304 -
2022-08-13 14:07:14,108 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:14] "[36mGET /css/app.61a069f3.css HTTP/1.1[0m" 304 -
2022-08-13 14:07:14,109 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:14] "[36mGET /js/app.19c66b8a.js HTTP/1.1[0m" 304 -
2022-08-13 14:07:14,435 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:14] "GET /js/chunk-vendors.79915abe.js.map HTTP/1.1" 200 -
2022-08-13 14:07:14,436 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:14] "GET /js/app.19c66b8a.js.map HTTP/1.1" 200 -
2022-08-13 14:07:14,460 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:14] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 14:07:14,460 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:14] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:07:14,483 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:14] "[36mGET /fonts/element-icons.ff18efd1.woff HTTP/1.1[0m" 304 -
2022-08-13 14:07:23,090 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:23] "[33mGET /wallet HTTP/1.1[0m" 404 -
2022-08-13 14:07:23,489 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:23] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 14:07:24,257 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:24] "[33mGET /wallet HTTP/1.1[0m" 404 -
2022-08-13 14:07:24,645 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:24] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 14:07:32,831 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:32] "[33mGET /wallet/ HTTP/1.1[0m" 404 -
2022-08-13 14:07:37,580 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1292 and this is thread id 13528.
2022-08-13 14:07:37,581 - ERROR - Exception closing connection <sqlite3.Connection object at 0x0000028ABD5D4B40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1292 and this is thread id 13528.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1292 and this is thread id 13528.
2022-08-13 14:07:37,583 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:37] "GET / HTTP/1.1" 200 -
2022-08-13 14:07:37,644 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:37] "[36mGET /js/chunk-vendors.79915abe.js HTTP/1.1[0m" 304 -
2022-08-13 14:07:37,646 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:37] "[36mGET /css/chunk-vendors.0b0c58b7.css HTTP/1.1[0m" 304 -
2022-08-13 14:07:37,651 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:37] "[36mGET /css/app.61a069f3.css HTTP/1.1[0m" 304 -
2022-08-13 14:07:37,653 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:37] "[36mGET /js/app.19c66b8a.js HTTP/1.1[0m" 304 -
2022-08-13 14:07:37,960 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:37] "GET /js/chunk-vendors.79915abe.js.map HTTP/1.1" 200 -
2022-08-13 14:07:37,961 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:37] "GET /js/app.19c66b8a.js.map HTTP/1.1" 200 -
2022-08-13 14:07:37,987 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:37] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:07:37,989 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:37] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 14:07:38,018 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:38] "[36mGET /fonts/element-icons.ff18efd1.woff HTTP/1.1[0m" 304 -
2022-08-13 14:07:51,646 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:51] "GET /css/796.900c8e84.css HTTP/1.1" 200 -
2022-08-13 14:07:51,647 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:51] "GET /js/796.4860069b.js HTTP/1.1" 200 -
2022-08-13 14:07:51,682 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:51] "GET /js/796.4860069b.js.map HTTP/1.1" 200 -
2022-08-13 14:07:54,641 - INFO - 127.0.0.1 - - [13/Aug/2022 14:07:54] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:08:35,823 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 8476 and this is thread id 4820.
2022-08-13 14:08:35,823 - ERROR - Exception closing connection <sqlite3.Connection object at 0x0000028ABD5D4B40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 8476 and this is thread id 4820.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 8476 and this is thread id 4820.
2022-08-13 14:08:35,824 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14720 and this is thread id 4820.
2022-08-13 14:08:35,824 - ERROR - Exception closing connection <sqlite3.Connection object at 0x0000028ABD5D4D40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14720 and this is thread id 4820.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14720 and this is thread id 4820.
2022-08-13 14:08:35,825 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1824 and this is thread id 4820.
2022-08-13 14:08:35,825 - ERROR - Exception closing connection <sqlite3.Connection object at 0x0000028ABD5D4940>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1824 and this is thread id 4820.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1824 and this is thread id 4820.
2022-08-13 14:08:38,470 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 14:08:47,061 - INFO - 127.0.0.1 - - [13/Aug/2022 14:08:47] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:08:55,589 - INFO - 127.0.0.1 - - [13/Aug/2022 14:08:55] "GET /css/829.084ff3a2.css HTTP/1.1" 200 -
2022-08-13 14:08:55,589 - INFO - 127.0.0.1 - - [13/Aug/2022 14:08:55] "GET /js/829.c4e82695.js HTTP/1.1" 200 -
2022-08-13 14:08:55,601 - INFO - 127.0.0.1 - - [13/Aug/2022 14:08:55] "GET /js/829.c4e82695.js.map HTTP/1.1" 200 -
2022-08-13 14:08:55,614 - INFO - 127.0.0.1 - - [13/Aug/2022 14:08:55] "[33mGET /api/balance_pay HTTP/1.1[0m" 404 -
2022-08-13 14:08:57,668 - INFO - 127.0.0.1 - - [13/Aug/2022 14:08:57] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:13:11,111 - INFO - 127.0.0.1 - - [13/Aug/2022 14:13:11] "[33mGET /api/balance_pay HTTP/1.1[0m" 404 -
2022-08-13 14:13:20,201 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 8600 and this is thread id 5000.
2022-08-13 14:13:20,202 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001F5E98B4E40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 8600 and this is thread id 5000.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 8600 and this is thread id 5000.
2022-08-13 14:13:20,205 - INFO - 127.0.0.1 - - [13/Aug/2022 14:13:20] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:18:49,400 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 5000 and this is thread id 3816.
2022-08-13 14:18:49,401 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001F5E98B4E40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 5000 and this is thread id 3816.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 5000 and this is thread id 3816.
2022-08-13 14:18:49,401 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13420 and this is thread id 3816.
2022-08-13 14:18:49,401 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001F5E98B4740>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13420 and this is thread id 3816.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13420 and this is thread id 3816.
2022-08-13 14:18:53,054 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 14:19:03,658 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:03] "[33mGET /wallet HTTP/1.1[0m" 404 -
2022-08-13 14:19:04,086 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:04] "GET /favicon.ico HTTP/1.1" 200 -
2022-08-13 14:19:11,156 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:11] "GET / HTTP/1.1" 200 -
2022-08-13 14:19:11,227 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:11] "GET /js/chunk-vendors.79915abe.js HTTP/1.1" 200 -
2022-08-13 14:19:11,232 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:11] "GET /css/chunk-vendors.0b0c58b7.css HTTP/1.1" 200 -
2022-08-13 14:19:11,234 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:11] "GET /css/app.13736bd7.css HTTP/1.1" 200 -
2022-08-13 14:19:11,236 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:11] "GET /js/app.70160ec0.js HTTP/1.1" 200 -
2022-08-13 14:19:11,525 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:11] "GET /js/chunk-vendors.79915abe.js.map HTTP/1.1" 200 -
2022-08-13 14:19:11,634 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:11] "GET /fonts/element-icons.ff18efd1.woff HTTP/1.1" 200 -
2022-08-13 14:19:11,638 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:11] "GET /js/app.70160ec0.js.map HTTP/1.1" 200 -
2022-08-13 14:19:11,648 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:11] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 14:19:11,649 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:11] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:19:36,338 - INFO - µ±Ç°Ä¸½ø³Ì: 17820
2022-08-13 14:19:36,341 - INFO - 127.0.0.1 - - [13/Aug/2022 14:19:36] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:19:36,343 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 11524 and this is thread id 14388.
2022-08-13 14:19:36,344 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000002566D7A4940>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 11524 and this is thread id 14388.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 11524 and this is thread id 14388.
2022-08-13 14:19:37,239 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 14:19:37,239 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/e811ddfc-1acf-11ed-90d3-a0510bad1688.key
2022-08-13 14:19:37,239 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:19:45,171 - INFO - {"address":"12ys6B8sDHhvdFoTC7paispCncCRuvADHoudL17x4tx3ADLNGKg","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 14:19:45,498 - INFO - ´´½¨³É¹¦
2022-08-13 14:19:45,512 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 14:19:45,513 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/ed006dc7-1acf-11ed-9f62-a0510bad1688.key
2022-08-13 14:19:45,513 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:19:53,207 - INFO - {"address":"14j1BP9zkV4fS8JuDJfi5HWHY8XhWHyfvYHBP6GJk3TLxLqpkUw","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 14:19:53,484 - INFO - ´´½¨³É¹¦
2022-08-13 14:19:53,496 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 14:19:53,497 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/f1c2b809-1acf-11ed-9773-a0510bad1688.key
2022-08-13 14:19:53,497 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:20:01,087 - INFO - {"address":"13EZuNssA94NpeePcKw1mJQj4EAsUUFukMmqi8bnb2ECwAToAgE","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 14:20:01,420 - INFO - ´´½¨³É¹¦
2022-08-13 14:20:01,438 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 14:20:01,439 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/f67e91ed-1acf-11ed-913e-a0510bad1688.key
2022-08-13 14:20:01,439 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:20:09,176 - INFO - {"address":"13PUmSFaYCbKBkmXfeHxqoHPVhFyWv85D52SF2WLDJqTRVQt3Js","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 14:20:09,508 - INFO - ´´½¨³É¹¦
2022-08-13 14:20:09,526 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 14:20:09,527 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/fb50b73a-1acf-11ed-be18-a0510bad1688.key
2022-08-13 14:20:09,527 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:20:17,267 - INFO - {"address":"13dgjAU9euRaDjHUDhWA5E61sYpNZg3geuK7zABKNxCkfesKA8H","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 14:20:17,605 - INFO - ´´½¨³É¹¦
2022-08-13 14:20:17,619 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 14:20:17,620 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/00239ec9-1ad0-11ed-ba8f-a0510bad1688.key
2022-08-13 14:20:17,620 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:20:25,386 - INFO - {"address":"14FCGzah5EAhnqDDqMERDZYAMwiTZNAB7TnoVDoESnUeCsPEAtD","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 14:20:25,660 - INFO - ´´½¨³É¹¦
2022-08-13 14:20:25,673 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 14:20:25,673 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/04f05d9e-1ad0-11ed-81dd-a0510bad1688.key
2022-08-13 14:20:25,673 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:20:33,387 - INFO - {"address":"14f3sh6hdQ6X5NxpzQ7Jr5DpkCeoXoakLz2xXqLwGX7tsLkzdGY","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 14:20:33,705 - INFO - ´´½¨³É¹¦
2022-08-13 14:20:33,720 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 14:20:33,721 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/09bc35e6-1ad0-11ed-bab3-a0510bad1688.key
2022-08-13 14:20:33,721 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:20:41,452 - INFO - {"address":"14dcXcsmkAsZ8bKPiRNxehsWUGM9d9EVyRn8jd5xwSFymq1Dr7e","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 14:20:41,776 - INFO - ´´½¨³É¹¦
2022-08-13 14:20:41,791 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 14:20:41,792 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/0e8bc8ab-1ad0-11ed-b38a-a0510bad1688.key
2022-08-13 14:20:41,792 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:20:49,504 - INFO - {"address":"14oppbbEi64ZjqRnbakj5v6k8WQJ3fxJw4Afdx4nfL9aCEZ3v25","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 14:20:49,828 - INFO - ´´½¨³É¹¦
2022-08-13 14:20:49,840 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 14:20:49,841 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  ./dataKeys/13582aef-1ad0-11ed-b874-a0510bad1688.key
2022-08-13 14:20:49,841 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:20:57,558 - INFO - {"address":"12yTBdVJ4jn3A1vsYXMUdUBg9ZgRtXkAGmFgyyinRsqXsQQySZM","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 14:20:57,858 - INFO - ´´½¨³É¹¦
2022-08-13 14:20:58,062 - INFO - 127.0.0.1 - - [13/Aug/2022 14:20:58] "POST /api/basics HTTP/1.1" 200 -
2022-08-13 14:21:08,773 - INFO - 127.0.0.1 - - [13/Aug/2022 14:21:08] "GET /css/123.d6d0f287.css HTTP/1.1" 200 -
2022-08-13 14:21:08,774 - INFO - 127.0.0.1 - - [13/Aug/2022 14:21:08] "GET /js/123.1af480c9.js HTTP/1.1" 200 -
2022-08-13 14:21:08,804 - INFO - 127.0.0.1 - - [13/Aug/2022 14:21:08] "GET /js/123.1af480c9.js.map HTTP/1.1" 200 -
2022-08-13 14:21:11,451 - INFO - 127.0.0.1 - - [13/Aug/2022 14:21:11] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:24:10,813 - INFO - 127.0.0.1 - - [13/Aug/2022 14:24:10] "GET /api/transfer?wallet=13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV HTTP/1.1" 200 -
2022-08-13 14:25:17,280 - INFO - 127.0.0.1 - - [13/Aug/2022 14:25:17] "GET /api/transfer?wallet=13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV HTTP/1.1" 200 -
2022-08-13 14:33:18,940 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 18128 and this is thread id 7100.
2022-08-13 14:33:18,940 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000002566D7A5740>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 18128 and this is thread id 7100.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 18128 and this is thread id 7100.
2022-08-13 14:33:18,941 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13704 and this is thread id 7100.
2022-08-13 14:33:18,941 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000002566D7A5B40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13704 and this is thread id 7100.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13704 and this is thread id 7100.
2022-08-13 14:33:18,942 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13564 and this is thread id 7100.
2022-08-13 14:33:18,942 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000002566D7A4B40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13564 and this is thread id 7100.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13564 and this is thread id 7100.
2022-08-13 14:33:18,943 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6524 and this is thread id 7100.
2022-08-13 14:33:18,943 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000002566D7A4D40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6524 and this is thread id 7100.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6524 and this is thread id 7100.
2022-08-13 14:33:20,473 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 14:33:27,325 - INFO - 127.0.0.1 - - [13/Aug/2022 14:33:27] "[31m[1mGET /api/transfer?wallet=13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV HTTP/1.1[0m" 400 -
2022-08-13 14:33:34,214 - INFO - 127.0.0.1 - - [13/Aug/2022 14:33:34] "[31m[1mGET /api/transfer?wallet=13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV HTTP/1.1[0m" 400 -
2022-08-13 14:38:47,543 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 14:39:05,359 - INFO - Ç®°ü:{}ÁÐ³öÈÈµã³É¹¦
2022-08-13 14:39:05,360 - INFO - 127.0.0.1 - - [13/Aug/2022 14:39:05] "GET /api/transfer?wallet=13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV HTTP/1.1" 200 -
2022-08-13 14:39:47,689 - INFO - Ç®°ü:{}ÁÐ³öÈÈµã³É¹¦
2022-08-13 14:39:47,689 - INFO - 127.0.0.1 - - [13/Aug/2022 14:39:47] "GET /api/transfer?wallet=13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV HTTP/1.1" 200 -
2022-08-13 14:42:30,948 - INFO - 127.0.0.1 - - [13/Aug/2022 14:42:30] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:47:29,939 - INFO - µ±Ç°Ä¸½ø³Ì: 11696
2022-08-13 14:47:29,942 - INFO - 127.0.0.1 - - [13/Aug/2022 14:47:29] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:47:29,951 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 10752 and this is thread id 11012.
2022-08-13 14:47:29,954 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001CEB9244C40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 10752 and this is thread id 11012.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 10752 and this is thread id 11012.
2022-08-13 14:47:30,890 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 14:47:30,890 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  D:/wallet/OK4/pyhelm1/newkey/cda4d5ff-1ad3-11ed-830f-a0510bad1688.key
2022-08-13 14:47:30,890 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:47:38,761 - INFO - {"address":"12zfmhb8fQgFJT7vzNW82fPDQF8CyGGerDBUakkWb8a8H2tqSpV","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 14:47:39,083 - INFO - ´´½¨³É¹¦
2022-08-13 14:47:39,096 - INFO - ¿ªÊ¼´´½¨ÐÂÇ®°ü
2022-08-13 14:47:39,097 - INFO - ´´½¨ÃüÁîÊÇ:helium-wallet --format json  create basic --output  D:/wallet/OK4/pyhelm1/newkey/d289158b-1ad3-11ed-b632-a0510bad1688.key
2022-08-13 14:47:39,097 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:47:47,070 - INFO - {"address":"14UgXPTeNcK6Ha2pW8mTxjmZLRUQiXCVATw38JTiHVGezcrkkb8","pwhash":"Argon2id13","sharded":false,"verify":true}
2022-08-13 14:47:47,397 - INFO - ´´½¨³É¹¦
2022-08-13 14:47:47,600 - INFO - 127.0.0.1 - - [13/Aug/2022 14:47:47] "POST /api/basics HTTP/1.1" 200 -
2022-08-13 14:47:59,364 - INFO - 127.0.0.1 - - [13/Aug/2022 14:47:59] "[33mGET /wallet HTTP/1.1[0m" 404 -
2022-08-13 14:47:59,822 - INFO - 127.0.0.1 - - [13/Aug/2022 14:47:59] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 14:48:05,584 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:05] "GET / HTTP/1.1" 200 -
2022-08-13 14:48:05,643 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:05] "[36mGET /js/chunk-vendors.79915abe.js HTTP/1.1[0m" 304 -
2022-08-13 14:48:05,647 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:05] "[36mGET /js/app.70160ec0.js HTTP/1.1[0m" 304 -
2022-08-13 14:48:05,648 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:05] "[36mGET /css/chunk-vendors.0b0c58b7.css HTTP/1.1[0m" 304 -
2022-08-13 14:48:05,649 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:05] "[36mGET /css/app.13736bd7.css HTTP/1.1[0m" 304 -
2022-08-13 14:48:05,996 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:05] "GET /js/app.70160ec0.js.map HTTP/1.1" 200 -
2022-08-13 14:48:05,997 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:05] "GET /js/chunk-vendors.79915abe.js.map HTTP/1.1" 200 -
2022-08-13 14:48:06,002 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:06] "[36mGET /fonts/element-icons.ff18efd1.woff HTTP/1.1[0m" 304 -
2022-08-13 14:48:06,018 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:06] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 14:48:06,019 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:06] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 14:48:44,929 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:44] "[36mGET /css/123.d6d0f287.css HTTP/1.1[0m" 304 -
2022-08-13 14:48:44,930 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:44] "[36mGET /js/123.1af480c9.js HTTP/1.1[0m" 304 -
2022-08-13 14:48:44,952 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:44] "GET /js/123.1af480c9.js.map HTTP/1.1" 200 -
2022-08-13 14:48:55,931 - INFO - Ç®°ü:{}ÁÐ³öÈÈµã³É¹¦
2022-08-13 14:48:55,931 - INFO - 127.0.0.1 - - [13/Aug/2022 14:48:55] "GET /api/transfer?wallet=13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV HTTP/1.1" 200 -
2022-08-13 14:56:35,371 - INFO - LST111009
2022-08-13 14:56:35,371 - INFO - ¿ªÊ¼×ªÒÆÈÈµã
2022-08-13 14:56:35,376 - INFO - source_hostpots:1
2022-08-13 14:56:35,377 - INFO - dest_wallet:14n6feKHiWLkYyuwW8ig7QAYE9Y8tFzWYNYvf79Ai33QmAp9VcM
2022-08-13 14:56:35,377 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 14:56:35,377 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  1  14n6feKHiWLkYyuwW8ig7QAYE9Y8tFzWYNYvf79Ai33QmAp9VcM --commit
2022-08-13 14:56:35,377 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:57:05,959 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x000001CEB94E4B20>
command: .\cmd.exe
args: ['.\\cmd.exe']
searcher: searcher_re:
    0: re.compile("Password:")
buffer (last 100 chars): 9Ai33QmAp9VcM --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
before (last 100 chars): 9Ai33QmAp9VcM --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 11696
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
2022-08-13 14:57:06,287 - INFO - source_hostpots:1
2022-08-13 14:57:06,287 - INFO - dest_wallet:13M4tVhdKxvPoXzv5ihC3Xg4n4EoM9kk9jaJpHeR5w82AUUViiM
2022-08-13 14:57:06,287 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 14:57:06,287 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  1  13M4tVhdKxvPoXzv5ihC3Xg4n4EoM9kk9jaJpHeR5w82AUUViiM --commit
2022-08-13 14:57:06,287 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:57:36,920 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x000001CEB93D41C0>
command: .\cmd.exe
args: ['.\\cmd.exe']
searcher: searcher_re:
    0: re.compile("Password:")
buffer (last 100 chars): eR5w82AUUViiM --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
before (last 100 chars): eR5w82AUUViiM --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 11696
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
2022-08-13 14:57:37,229 - INFO - source_hostpots:2
2022-08-13 14:57:37,229 - INFO - dest_wallet:14TGU4XGmQMbLqRz5G3a3c9Eip6WXnxYJHqzfxWnwuRsu8AMVb7
2022-08-13 14:57:37,229 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 14:57:37,229 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  2  14TGU4XGmQMbLqRz5G3a3c9Eip6WXnxYJHqzfxWnwuRsu8AMVb7 --commit
2022-08-13 14:57:37,230 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:58:07,802 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x000001CEB93D41C0>
command: .\cmd.exe
args: ['.\\cmd.exe']
searcher: searcher_re:
    0: re.compile("Password:")
buffer (last 100 chars): WnwuRsu8AMVb7 --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
before (last 100 chars): WnwuRsu8AMVb7 --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 11696
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
2022-08-13 14:58:08,119 - INFO - source_hostpots:K
2022-08-13 14:58:08,119 - INFO - dest_wallet:12ys6B8sDHhvdFoTC7paispCncCRuvADHoudL17x4tx3ADLNGKg
2022-08-13 14:58:08,119 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 14:58:08,119 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  K  12ys6B8sDHhvdFoTC7paispCncCRuvADHoudL17x4tx3ADLNGKg --commit
2022-08-13 14:58:08,119 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:58:38,761 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x000001CEB93D41C0>
command: .\cmd.exe
args: ['.\\cmd.exe']
searcher: searcher_re:
    0: re.compile("Password:")
buffer (last 100 chars): 7x4tx3ADLNGKg --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
before (last 100 chars): 7x4tx3ADLNGKg --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 11696
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
2022-08-13 14:58:39,112 - INFO - source_hostpots:e
2022-08-13 14:58:39,112 - INFO - dest_wallet:14j1BP9zkV4fS8JuDJfi5HWHY8XhWHyfvYHBP6GJk3TLxLqpkUw
2022-08-13 14:58:39,112 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 14:58:39,112 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  e  14j1BP9zkV4fS8JuDJfi5HWHY8XhWHyfvYHBP6GJk3TLxLqpkUw --commit
2022-08-13 14:58:39,112 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:59:09,743 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x000001CEB93D41C0>
command: .\cmd.exe
args: ['.\\cmd.exe']
searcher: searcher_re:
    0: re.compile("Password:")
buffer (last 100 chars): GJk3TLxLqpkUw --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
before (last 100 chars): GJk3TLxLqpkUw --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 11696
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
2022-08-13 14:59:10,087 - INFO - source_hostpots:3
2022-08-13 14:59:10,087 - INFO - dest_wallet:13EZuNssA94NpeePcKw1mJQj4EAsUUFukMmqi8bnb2ECwAToAgE
2022-08-13 14:59:10,087 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 14:59:10,087 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  3  13EZuNssA94NpeePcKw1mJQj4EAsUUFukMmqi8bnb2ECwAToAgE --commit
2022-08-13 14:59:10,087 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:59:40,678 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x000001CEB93D41C0>
command: .\cmd.exe
args: ['.\\cmd.exe']
searcher: searcher_re:
    0: re.compile("Password:")
buffer (last 100 chars): bnb2ECwAToAgE --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
before (last 100 chars): bnb2ECwAToAgE --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 11696
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
2022-08-13 14:59:41,011 - INFO - source_hostpots:m
2022-08-13 14:59:41,011 - INFO - dest_wallet:13PUmSFaYCbKBkmXfeHxqoHPVhFyWv85D52SF2WLDJqTRVQt3Js
2022-08-13 14:59:41,011 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 14:59:41,011 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  m  13PUmSFaYCbKBkmXfeHxqoHPVhFyWv85D52SF2WLDJqTRVQt3Js --commit
2022-08-13 14:59:41,011 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 14:59:52,504 - INFO - Ç®°ü:{}ÁÐ³öÈÈµã³É¹¦
2022-08-13 14:59:52,504 - INFO - 127.0.0.1 - - [13/Aug/2022 14:59:52] "GET /api/transfer?wallet=13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV HTTP/1.1" 200 -
2022-08-13 15:00:11,651 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x000001CEB93D41C0>
command: .\cmd.exe
args: ['.\\cmd.exe']
searcher: searcher_re:
    0: re.compile("Password:")
buffer (last 100 chars): WLDJqTRVQt3Js --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
before (last 100 chars): WLDJqTRVQt3Js --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 11696
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
2022-08-13 15:00:11,990 - INFO - source_hostpots:n
2022-08-13 15:00:11,990 - INFO - dest_wallet:13dgjAU9euRaDjHUDhWA5E61sYpNZg3geuK7zABKNxCkfesKA8H
2022-08-13 15:00:11,990 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 15:00:11,990 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  n  13dgjAU9euRaDjHUDhWA5E61sYpNZg3geuK7zABKNxCkfesKA8H --commit
2022-08-13 15:00:11,990 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 15:00:42,625 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x000001CEB93D41C0>
command: .\cmd.exe
args: ['.\\cmd.exe']
searcher: searcher_re:
    0: re.compile("Password:")
buffer (last 100 chars): BKNxCkfesKA8H --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
before (last 100 chars): BKNxCkfesKA8H --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 11696
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
2022-08-13 15:00:42,976 - INFO - source_hostpots:G
2022-08-13 15:00:42,977 - INFO - dest_wallet:14FCGzah5EAhnqDDqMERDZYAMwiTZNAB7TnoVDoESnUeCsPEAtD
2022-08-13 15:00:42,977 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 15:00:42,977 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  G  14FCGzah5EAhnqDDqMERDZYAMwiTZNAB7TnoVDoESnUeCsPEAtD --commit
2022-08-13 15:00:42,977 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 15:01:13,612 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x000001CEB93D41C0>
command: .\cmd.exe
args: ['.\\cmd.exe']
searcher: searcher_re:
    0: re.compile("Password:")
buffer (last 100 chars): oESnUeCsPEAtD --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
before (last 100 chars): oESnUeCsPEAtD --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 11696
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
2022-08-13 15:01:13,965 - INFO - source_hostpots:K
2022-08-13 15:01:13,965 - INFO - dest_wallet:14f3sh6hdQ6X5NxpzQ7Jr5DpkCeoXoakLz2xXqLwGX7tsLkzdGY
2022-08-13 15:01:13,965 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 15:01:13,966 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  K  14f3sh6hdQ6X5NxpzQ7Jr5DpkCeoXoakLz2xXqLwGX7tsLkzdGY --commit
2022-08-13 15:01:13,966 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 15:01:44,613 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x000001CEB93D41C0>
command: .\cmd.exe
args: ['.\\cmd.exe']
searcher: searcher_re:
    0: re.compile("Password:")
buffer (last 100 chars): LwGX7tsLkzdGY --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
before (last 100 chars): LwGX7tsLkzdGY --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 11696
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
2022-08-13 15:01:44,940 - INFO - source_hostpots:T
2022-08-13 15:01:44,940 - INFO - dest_wallet:14dcXcsmkAsZ8bKPiRNxehsWUGM9d9EVyRn8jd5xwSFymq1Dr7e
2022-08-13 15:01:44,941 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 15:01:44,941 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  T  14dcXcsmkAsZ8bKPiRNxehsWUGM9d9EVyRn8jd5xwSFymq1Dr7e --commit
2022-08-13 15:01:44,941 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 15:02:15,589 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x000001CEB93D41C0>
command: .\cmd.exe
args: ['.\\cmd.exe']
searcher: searcher_re:
    0: re.compile("Password:")
buffer (last 100 chars): 5xwSFymq1Dr7e --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
before (last 100 chars): 5xwSFymq1Dr7e --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 11696
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
2022-08-13 15:02:15,921 - INFO - source_hostpots:j
2022-08-13 15:02:15,921 - INFO - dest_wallet:14oppbbEi64ZjqRnbakj5v6k8WQJ3fxJw4Afdx4nfL9aCEZ3v25
2022-08-13 15:02:15,921 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 15:02:15,921 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  j  14oppbbEi64ZjqRnbakj5v6k8WQJ3fxJw4Afdx4nfL9aCEZ3v25 --commit
2022-08-13 15:02:15,921 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 15:02:46,580 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:Timeout exceeded in expect_any().
<wexpect.host.SpawnPipe object at 0x000001CEB93D41C0>
command: .\cmd.exe
args: ['.\\cmd.exe']
searcher: searcher_re:
    0: re.compile("Password:")
buffer (last 100 chars): 4nfL9aCEZ3v25 --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
before (last 100 chars): 4nfL9aCEZ3v25 --commit
error: Invalid value for '<gateway>': decode error

D:\wallet\OK4\pyhelm1>
after: <class 'wexpect.wexpect_util.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
host_pid: 11696
child_fd: None
closed: False
timeout: 30
delimiter: <class 'wexpect.wexpect_util.EOF'>
maxread: 60000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.1
delayafterterminate: 2
2022-08-13 15:02:46,909 - INFO - source_hostpots:a
2022-08-13 15:02:46,910 - INFO - dest_wallet:12yTBdVJ4jn3A1vsYXMUdUBg9ZgRtXkAGmFgyyinRsqXsQQySZM
2022-08-13 15:02:46,910 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 15:02:46,910 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  a  12yTBdVJ4jn3A1vsYXMUdUBg9ZgRtXkAGmFgyyinRsqXsQQySZM --commit
2022-08-13 15:02:46,910 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 15:02:53,831 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 18348 and this is thread id 10084.
2022-08-13 15:02:53,831 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001CEB9244740>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 18348 and this is thread id 10084.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 18348 and this is thread id 10084.
2022-08-13 15:02:53,831 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 2228 and this is thread id 10084.
2022-08-13 15:02:53,832 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001CEB9244940>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 2228 and this is thread id 10084.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 2228 and this is thread id 10084.
2022-08-13 15:03:10,513 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 15:03:56,379 - INFO - LST111009
2022-08-13 15:03:56,388 - INFO - 127.0.0.1 - - [13/Aug/2022 15:03:56] "[35m[1mPOST /api/transfer HTTP/1.1[0m" 500 -
2022-08-13 15:04:35,831 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 15:04:47,010 - INFO - LST111009
2022-08-13 15:04:47,011 - INFO - 127.0.0.1 - - [13/Aug/2022 15:04:47] "POST /api/transfer HTTP/1.1" 200 -
2022-08-13 15:05:23,769 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 15:05:34,952 - INFO - LST111009
2022-08-13 15:05:34,953 - INFO - 127.0.0.1 - - [13/Aug/2022 15:05:34] "POST /api/transfer HTTP/1.1" 200 -
2022-08-13 15:06:24,369 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 15:06:39,520 - INFO - transfer
2022-08-13 15:06:39,520 - INFO - LST111009
2022-08-13 15:06:39,520 - INFO - ['112Ke3mnGKTja5FxJe1eoQGRhZW92hDVL3tu9GcsE4RFdzGkY27n', '11k4EcGhZ4FEPH1NmGeRbUBv66HUUAjGc7KJXy66SfwMZsmJLia']
2022-08-13 15:06:39,520 - INFO - 13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV
2022-08-13 15:06:39,520 - INFO - ¿ªÊ¼×ªÒÆÈÈµã
2022-08-13 15:06:39,525 - INFO - source_hostpots:112Ke3mnGKTja5FxJe1eoQGRhZW92hDVL3tu9GcsE4RFdzGkY27n
2022-08-13 15:06:39,525 - INFO - dest_wallet:14n6feKHiWLkYyuwW8ig7QAYE9Y8tFzWYNYvf79Ai33QmAp9VcM
2022-08-13 15:06:39,525 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 15:06:39,525 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  112Ke3mnGKTja5FxJe1eoQGRhZW92hDVL3tu9GcsE4RFdzGkY27n  14n6feKHiWLkYyuwW8ig7QAYE9Y8tFzWYNYvf79Ai33QmAp9VcM --commit
2022-08-13 15:06:39,525 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 15:06:47,682 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:list index out of range
2022-08-13 15:06:47,968 - INFO - source_hostpots:11k4EcGhZ4FEPH1NmGeRbUBv66HUUAjGc7KJXy66SfwMZsmJLia
2022-08-13 15:06:47,968 - INFO - dest_wallet:13M4tVhdKxvPoXzv5ihC3Xg4n4EoM9kk9jaJpHeR5w82AUUViiM
2022-08-13 15:06:47,968 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 15:06:47,968 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  11k4EcGhZ4FEPH1NmGeRbUBv66HUUAjGc7KJXy66SfwMZsmJLia  13M4tVhdKxvPoXzv5ihC3Xg4n4EoM9kk9jaJpHeR5w82AUUViiM --commit
2022-08-13 15:06:47,968 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 15:06:58,158 - ERROR - Ö´ÐÐ×ªÒÆÈÈµãÊ§°Ü:list index out of range
2022-08-13 15:06:58,459 - INFO - 127.0.0.1 - - [13/Aug/2022 15:06:58] "POST /api/transfer HTTP/1.1" 200 -
2022-08-13 15:11:32,313 - INFO - transfer
2022-08-13 15:11:32,313 - INFO - 123456
2022-08-13 15:11:32,313 - INFO - ['112Ke3mnGKTja5FxJe1eoQGRhZW92hDVL3tu9GcsE4RFdzGkY27n', '11k4EcGhZ4FEPH1NmGeRbUBv66HUUAjGc7KJXy66SfwMZsmJLia']
2022-08-13 15:11:32,314 - INFO - 13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV
2022-08-13 15:11:32,314 - INFO - ¿ªÊ¼×ªÒÆÈÈµã
2022-08-13 15:11:32,316 - INFO - source_hostpots:112Ke3mnGKTja5FxJe1eoQGRhZW92hDVL3tu9GcsE4RFdzGkY27n
2022-08-13 15:11:32,316 - INFO - dest_wallet:14n6feKHiWLkYyuwW8ig7QAYE9Y8tFzWYNYvf79Ai33QmAp9VcM
2022-08-13 15:11:32,316 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 15:11:32,316 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  112Ke3mnGKTja5FxJe1eoQGRhZW92hDVL3tu9GcsE4RFdzGkY27n  14n6feKHiWLkYyuwW8ig7QAYE9Y8tFzWYNYvf79Ai33QmAp9VcM --commit
2022-08-13 15:11:32,316 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 15:11:41,433 - INFO - {"address":"112Ke3mnGKTja5FxJe1eoQGRhZW92hDVL3tu9GcsE4RFdzGkY27n","fee":40000,"hash":"KELjTeBRTzbh_UkaZGg3qQnnz6jwacBC7oCsMjeBmpM","new_owner":"14n6feKHiWLkYyuwW8ig7QAYE9Y8tFzWYNYvf79Ai33QmAp9VcM","nonce":4,"txn":"ogKxAQohAK4EhfImYN4dtVyKcFqNaDWiTitUzRqgZEld6JEgZR6GEiEBfdTthalM2oTXRlboykgInKPP/MmwnZUqQ5Q+kKpXAxQaQMLLiXNrlVFb+y8KZ2VpQUY+jkI2MGLdv/8nh9gCidArSGLZTQoJXWwVwZ+BFJLFfzMu45RCsbLKY90+drSizAMiIQHxfPVGwuhLYCE1e643YOZF4T15bsCDL8OUs4w0mcYOuyjAuAIwBA=="}
2022-08-13 15:11:41,433 - INFO - {'address': '112Ke3mnGKTja5FxJe1eoQGRhZW92hDVL3tu9GcsE4RFdzGkY27n', 'fee': 40000, 'hash': 'KELjTeBRTzbh_UkaZGg3qQnnz6jwacBC7oCsMjeBmpM', 'new_owner': '14n6feKHiWLkYyuwW8ig7QAYE9Y8tFzWYNYvf79Ai33QmAp9VcM', 'nonce': 4, 'txn': 'ogKxAQohAK4EhfImYN4dtVyKcFqNaDWiTitUzRqgZEld6JEgZR6GEiEBfdTthalM2oTXRlboykgInKPP/MmwnZUqQ5Q+kKpXAxQaQMLLiXNrlVFb+y8KZ2VpQUY+jkI2MGLdv/8nh9gCidArSGLZTQoJXWwVwZ+BFJLFfzMu45RCsbLKY90+drSizAMiIQHxfPVGwuhLYCE1e643YOZF4T15bsCDL8OUs4w0mcYOuyjAuAIwBA=='}
2022-08-13 15:11:41,771 - INFO - Ö´ÐÐ×ªÒÆÈÈµã³É¹¦:112Ke3mnGKTja5FxJe1eoQGRhZW92hDVL3tu9GcsE4RFdzGkY27n
2022-08-13 15:11:41,771 - INFO - source_hostpots:11k4EcGhZ4FEPH1NmGeRbUBv66HUUAjGc7KJXy66SfwMZsmJLia
2022-08-13 15:11:41,771 - INFO - dest_wallet:13M4tVhdKxvPoXzv5ihC3Xg4n4EoM9kk9jaJpHeR5w82AUUViiM
2022-08-13 15:11:41,771 - INFO - D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key
2022-08-13 15:11:41,771 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  hotspots transfer  11k4EcGhZ4FEPH1NmGeRbUBv66HUUAjGc7KJXy66SfwMZsmJLia  13M4tVhdKxvPoXzv5ihC3Xg4n4EoM9kk9jaJpHeR5w82AUUViiM --commit
2022-08-13 15:11:41,771 - INFO - ¿ªÊ¼Ö´ÐÐÃüÁî
2022-08-13 15:11:51,701 - INFO - {"address":"11k4EcGhZ4FEPH1NmGeRbUBv66HUUAjGc7KJXy66SfwMZsmJLia","fee":40000,"hash":"Kia2sExEF4amX-ZZouE7nqXrDzIWYhTpimujAcbLj24","new_owner":"13M4tVhdKxvPoXzv5ihC3Xg4n4EoM9kk9jaJpHeR5w82AUUViiM","nonce":5,"txn":"ogKxAQohAGHDbZ+IjfhyROQcu7qFZHm36n5tdhB39I5OZLDBNGfMEiEBfdTthalM2oTXRlboykgInKPP/MmwnZUqQ5Q+kKpXAxQaQPBl1EZ3um5VHx+kE575QGC0ueXI73BwDfJ0i/Ks7IvBVBSWcXpVAEplG1zV3JL58/iGHSO07hKq9Er95zyxmwoiIQE09POJ1KE8a7kvmNd1zDkzIeLamIkWL8mjeIfyjIxX3CjAuAIwBQ=="}
2022-08-13 15:11:51,701 - INFO - {'address': '11k4EcGhZ4FEPH1NmGeRbUBv66HUUAjGc7KJXy66SfwMZsmJLia', 'fee': 40000, 'hash': 'Kia2sExEF4amX-ZZouE7nqXrDzIWYhTpimujAcbLj24', 'new_owner': '13M4tVhdKxvPoXzv5ihC3Xg4n4EoM9kk9jaJpHeR5w82AUUViiM', 'nonce': 5, 'txn': 'ogKxAQohAGHDbZ+IjfhyROQcu7qFZHm36n5tdhB39I5OZLDBNGfMEiEBfdTthalM2oTXRlboykgInKPP/MmwnZUqQ5Q+kKpXAxQaQPBl1EZ3um5VHx+kE575QGC0ueXI73BwDfJ0i/Ks7IvBVBSWcXpVAEplG1zV3JL58/iGHSO07hKq9Er95zyxmwoiIQE09POJ1KE8a7kvmNd1zDkzIeLamIkWL8mjeIfyjIxX3CjAuAIwBQ=='}
2022-08-13 15:11:52,027 - INFO - Ö´ÐÐ×ªÒÆÈÈµã³É¹¦:11k4EcGhZ4FEPH1NmGeRbUBv66HUUAjGc7KJXy66SfwMZsmJLia
2022-08-13 15:11:52,028 - INFO - 127.0.0.1 - - [13/Aug/2022 15:11:52] "POST /api/transfer HTTP/1.1" 200 -
2022-08-13 15:35:09,645 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 15:35:39,411 - INFO - transfer
2022-08-13 15:35:39,411 - INFO - 1111111
2022-08-13 15:35:39,411 - INFO - 
2022-08-13 15:35:39,411 - INFO - 123456
2022-08-13 15:35:39,411 - INFO - ['112Ke3mnGKTja5FxJe1eoQGRhZW92hDVL3tu9GcsE4RFdzGkY27n', '11k4EcGhZ4FEPH1NmGeRbUBv66HUUAjGc7KJXy66SfwMZsmJLia']
2022-08-13 15:35:39,411 - INFO - 13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV
2022-08-13 15:35:39,411 - INFO - 127.0.0.1 - - [13/Aug/2022 15:35:39] "POST /api/transfer HTTP/1.1" 200 -
2022-08-13 15:36:36,349 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 15:36:43,973 - INFO - transfer
2022-08-13 15:36:43,973 - INFO - 22222222
2022-08-13 15:36:43,973 - INFO - <FileStorage: 'des_new.txt' ('text/plain')>
2022-08-13 15:36:43,974 - INFO - 123456
2022-08-13 15:36:43,974 - INFO - ['112Ke3mnGKTja5FxJe1eoQGRhZW92hDVL3tu9GcsE4RFdzGkY27n', '11k4EcGhZ4FEPH1NmGeRbUBv66HUUAjGc7KJXy66SfwMZsmJLia']
2022-08-13 15:36:43,974 - INFO - 13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV
2022-08-13 15:36:43,974 - INFO - 127.0.0.1 - - [13/Aug/2022 15:36:43] "POST /api/transfer HTTP/1.1" 200 -
2022-08-13 15:38:32,333 - INFO - 127.0.0.1 - - [13/Aug/2022 15:38:32] "GET /css/829.084ff3a2.css HTTP/1.1" 200 -
2022-08-13 15:38:32,334 - INFO - 127.0.0.1 - - [13/Aug/2022 15:38:32] "GET /js/829.67f5cc77.js HTTP/1.1" 200 -
2022-08-13 15:38:32,380 - INFO - 127.0.0.1 - - [13/Aug/2022 15:38:32] "GET /js/829.67f5cc77.js.map HTTP/1.1" 200 -
2022-08-13 15:38:32,425 - INFO - 127.0.0.1 - - [13/Aug/2022 15:38:32] "[35m[1mGET /api/balance_pay HTTP/1.1[0m" 500 -
2022-08-13 15:39:03,548 - INFO - Ç®°ü:{}ÁÐ³öÈÈµã³É¹¦
2022-08-13 15:39:03,548 - INFO - 127.0.0.1 - - [13/Aug/2022 15:39:03] "GET /api/transfer?wallet=13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV HTTP/1.1" 200 -
2022-08-13 15:39:08,284 - INFO - 127.0.0.1 - - [13/Aug/2022 15:39:08] "[35m[1mGET /api/balance_pay HTTP/1.1[0m" 500 -
2022-08-13 15:43:55,543 - INFO - 127.0.0.1 - - [13/Aug/2022 15:43:55] "POST /api/balance_pay HTTP/1.1" 200 -
2022-08-13 15:45:19,350 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13484 and this is thread id 16220.
2022-08-13 15:45:19,352 - ERROR - Exception closing connection <sqlite3.Connection object at 0x0000023E2F584B40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13484 and this is thread id 16220.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13484 and this is thread id 16220.
2022-08-13 15:45:19,352 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 12976 and this is thread id 16220.
2022-08-13 15:45:19,353 - ERROR - Exception closing connection <sqlite3.Connection object at 0x0000023E2F584840>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 12976 and this is thread id 16220.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 12976 and this is thread id 16220.
2022-08-13 15:45:23,717 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 15:45:54,787 - INFO - ¿ªÊ¼×ªÕË
2022-08-13 15:45:58,696 - INFO - Ç®°üÃû³Æ:13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV,Ç®°ü½ð¶î: 2.10226569
2022-08-13 15:45:58,696 - INFO - ¿ªÊ¼×ªÕË
2022-08-13 15:45:58,696 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/1/13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  pay one  13HL77iS4Jy34X5dXmDQ4t53ZS5Ttzkei5qfuXqZpRxE1vh4PFU  2.06226569 --commit
2022-08-13 15:45:58,696 - INFO - ±¾´Î×ªÕË½ð¶î:2.06226569
2022-08-13 15:45:58,696 - INFO - Ç®°üÃû³Æ:13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV,Ç®°ü½ð¶î: 2.06226569
2022-08-13 15:46:08,869 - INFO - [hidden]{"fee":35000,"hash":"R_uSvxHRLUHyAPwFT8ls484FTZQD-VBBn1PowL2GArs","nonce":3,"payments":[{"amount":2.06226569,"memo":"AAAAAAAAAAA=","payee":"13HL77iS4Jy34X5dXmDQ4t53ZS5Ttzkei5qfuXqZpRxE1vh4PFU"}],"txn":"wgGVAQohAX3U7YWpTNqE10ZW6MpICJyjz/zJsJ2VKkOUPpCqVwMUEigKIQEseFiB8IgaZXuR1duxhCwcXAaV4ZVDKcRt7NXPmBJEehCJiatiGLiRAiADKkDBWATEetSmo7ijtCx0tKttylJWS08/3anQRm5UKyovgQOywBSqs95/XEqG8yx9bid4074WyWOPsKlQSu7dGEcF"}D:\wallet\OK4\pyhelm1
2022-08-13 15:46:09,159 - INFO - 127.0.0.1 - - [13/Aug/2022 15:46:09] "POST /api/balance_pay HTTP/1.1" 200 -
2022-08-13 15:47:30,938 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:30] "GET / HTTP/1.1" 200 -
2022-08-13 15:47:31,057 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:31] "[36mGET /js/chunk-vendors.79915abe.js HTTP/1.1[0m" 304 -
2022-08-13 15:47:31,062 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:31] "[36mGET /js/app.70160ec0.js HTTP/1.1[0m" 304 -
2022-08-13 15:47:31,066 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:31] "[36mGET /css/app.13736bd7.css HTTP/1.1[0m" 304 -
2022-08-13 15:47:31,067 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:31] "[36mGET /css/chunk-vendors.0b0c58b7.css HTTP/1.1[0m" 304 -
2022-08-13 15:47:31,344 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:31] "GET /js/chunk-vendors.79915abe.js.map HTTP/1.1" 200 -
2022-08-13 15:47:31,346 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:31] "GET /js/app.70160ec0.js.map HTTP/1.1" 200 -
2022-08-13 15:47:31,371 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:31] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 15:47:31,372 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:31] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 15:47:31,413 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:31] "[36mGET /fonts/element-icons.ff18efd1.woff HTTP/1.1[0m" 304 -
2022-08-13 15:47:33,298 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:33] "[36mGET /css/829.084ff3a2.css HTTP/1.1[0m" 304 -
2022-08-13 15:47:33,299 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:33] "[36mGET /js/829.67f5cc77.js HTTP/1.1[0m" 304 -
2022-08-13 15:47:33,314 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:33] "GET /js/829.67f5cc77.js.map HTTP/1.1" 200 -
2022-08-13 15:47:33,348 - INFO - 127.0.0.1 - - [13/Aug/2022 15:47:33] "[35m[1mGET /api/balance_pay HTTP/1.1[0m" 500 -
2022-08-13 15:49:24,744 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 3020 and this is thread id 18420.
2022-08-13 15:49:24,746 - ERROR - Exception closing connection <sqlite3.Connection object at 0x00000270CE1D4C40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 3020 and this is thread id 18420.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 3020 and this is thread id 18420.
2022-08-13 15:49:24,747 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 16284 and this is thread id 18420.
2022-08-13 15:49:24,747 - ERROR - Exception closing connection <sqlite3.Connection object at 0x00000270CE1D4B40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 16284 and this is thread id 18420.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 16284 and this is thread id 18420.
2022-08-13 15:49:26,578 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 15:49:30,887 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:30] "[33mGET /money HTTP/1.1[0m" 404 -
2022-08-13 15:49:31,313 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:31] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 15:49:34,428 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:34] "GET / HTTP/1.1" 200 -
2022-08-13 15:49:34,476 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:34] "[36mGET /js/chunk-vendors.79915abe.js HTTP/1.1[0m" 304 -
2022-08-13 15:49:34,479 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:34] "[36mGET /css/chunk-vendors.0b0c58b7.css HTTP/1.1[0m" 304 -
2022-08-13 15:49:34,482 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:34] "[36mGET /css/app.13736bd7.css HTTP/1.1[0m" 304 -
2022-08-13 15:49:34,499 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:34] "[36mGET /js/app.70160ec0.js HTTP/1.1[0m" 304 -
2022-08-13 15:49:34,810 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:34] "GET /js/chunk-vendors.79915abe.js.map HTTP/1.1" 200 -
2022-08-13 15:49:34,811 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:34] "GET /js/app.70160ec0.js.map HTTP/1.1" 200 -
2022-08-13 15:49:34,815 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:34] "[36mGET /fonts/element-icons.ff18efd1.woff HTTP/1.1[0m" 304 -
2022-08-13 15:49:34,833 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:34] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 15:49:34,834 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:34] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 15:49:36,689 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:36] "[36mGET /css/829.084ff3a2.css HTTP/1.1[0m" 304 -
2022-08-13 15:49:36,690 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:36] "[36mGET /js/829.67f5cc77.js HTTP/1.1[0m" 304 -
2022-08-13 15:49:36,709 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:36] "GET /js/829.67f5cc77.js.map HTTP/1.1" 200 -
2022-08-13 15:49:36,739 - INFO - 127.0.0.1 - - [13/Aug/2022 15:49:36] "GET /api/balance_pay HTTP/1.1" 200 -
2022-08-13 15:51:12,107 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14676 and this is thread id 1468.
2022-08-13 15:51:12,108 - ERROR - Exception closing connection <sqlite3.Connection object at 0x00000184A0C34D40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14676 and this is thread id 1468.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14676 and this is thread id 1468.
2022-08-13 15:51:12,108 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 17312 and this is thread id 1468.
2022-08-13 15:51:12,109 - ERROR - Exception closing connection <sqlite3.Connection object at 0x00000184A0C34B40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 17312 and this is thread id 1468.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 17312 and this is thread id 1468.
2022-08-13 15:51:13,563 - INFO -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2022-08-13 15:51:27,707 - INFO - 127.0.0.1 - - [13/Aug/2022 15:51:27] "[36mGET /js/123.1af480c9.js HTTP/1.1[0m" 304 -
2022-08-13 15:51:27,708 - INFO - 127.0.0.1 - - [13/Aug/2022 15:51:27] "[36mGET /css/123.d6d0f287.css HTTP/1.1[0m" 304 -
2022-08-13 15:51:27,721 - INFO - 127.0.0.1 - - [13/Aug/2022 15:51:27] "GET /js/123.1af480c9.js.map HTTP/1.1" 200 -
2022-08-13 15:51:28,702 - INFO - 127.0.0.1 - - [13/Aug/2022 15:51:28] "GET /api/balance_pay HTTP/1.1" 200 -
2022-08-13 16:06:26,888 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:26] "[33mGET /money HTTP/1.1[0m" 404 -
2022-08-13 16:06:27,308 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:27] "GET /favicon.ico HTTP/1.1" 200 -
2022-08-13 16:06:30,366 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:30] "GET / HTTP/1.1" 200 -
2022-08-13 16:06:30,411 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:30] "GET /js/chunk-vendors.79915abe.js HTTP/1.1" 200 -
2022-08-13 16:06:30,413 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:30] "GET /css/chunk-vendors.0b0c58b7.css HTTP/1.1" 200 -
2022-08-13 16:06:30,418 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:30] "GET /css/app.13736bd7.css HTTP/1.1" 200 -
2022-08-13 16:06:30,438 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:30] "GET /js/app.61820000.js HTTP/1.1" 200 -
2022-08-13 16:06:30,685 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:30] "GET /js/chunk-vendors.79915abe.js.map HTTP/1.1" 200 -
2022-08-13 16:06:30,836 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:30] "GET /js/app.61820000.js.map HTTP/1.1" 200 -
2022-08-13 16:06:30,842 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:30] "GET /fonts/element-icons.ff18efd1.woff HTTP/1.1" 200 -
2022-08-13 16:06:30,853 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:30] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 16:06:30,854 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:30] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 16:06:33,446 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:33] "GET /css/746.4039226c.css HTTP/1.1" 200 -
2022-08-13 16:06:33,447 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:33] "GET /js/746.d934ea50.js HTTP/1.1" 200 -
2022-08-13 16:06:33,466 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:33] "GET /js/746.d934ea50.js.map HTTP/1.1" 200 -
2022-08-13 16:06:33,489 - INFO - 127.0.0.1 - - [13/Aug/2022 16:06:33] "GET /api/balance_pay HTTP/1.1" 200 -
2022-08-13 16:07:53,289 - INFO - 127.0.0.1 - - [13/Aug/2022 16:07:53] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 18:49:19,254 - INFO - 127.0.0.1 - - [13/Aug/2022 18:49:19] "[33mGET /wallet HTTP/1.1[0m" 404 -
2022-08-13 18:49:19,597 - INFO - 127.0.0.1 - - [13/Aug/2022 18:49:19] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 18:51:27,901 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:27] "GET / HTTP/1.1" 200 -
2022-08-13 18:51:27,944 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:27] "[36mGET /js/chunk-vendors.79915abe.js HTTP/1.1[0m" 304 -
2022-08-13 18:51:27,949 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:27] "[36mGET /css/chunk-vendors.0b0c58b7.css HTTP/1.1[0m" 304 -
2022-08-13 18:51:27,950 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:27] "[36mGET /css/app.13736bd7.css HTTP/1.1[0m" 304 -
2022-08-13 18:51:27,952 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:27] "[36mGET /js/app.61820000.js HTTP/1.1[0m" 304 -
2022-08-13 18:51:28,233 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1520 and this is thread id 12536.
2022-08-13 18:51:28,233 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:28] "GET /js/chunk-vendors.79915abe.js.map HTTP/1.1" 200 -
2022-08-13 18:51:28,235 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001E3F8F15340>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1520 and this is thread id 12536.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1520 and this is thread id 12536.
2022-08-13 18:51:28,235 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6700 and this is thread id 12536.
2022-08-13 18:51:28,235 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001E3F8F14B40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6700 and this is thread id 12536.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6700 and this is thread id 12536.
2022-08-13 18:51:28,236 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:28] "GET /js/app.61820000.js.map HTTP/1.1" 200 -
2022-08-13 18:51:28,251 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:28] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
2022-08-13 18:51:28,251 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:28] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 18:51:28,274 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:28] "[36mGET /fonts/element-icons.ff18efd1.woff HTTP/1.1[0m" 304 -
2022-08-13 18:51:31,501 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:31] "GET /css/123.d6d0f287.css HTTP/1.1" 200 -
2022-08-13 18:51:31,502 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:31] "GET /js/123.1af480c9.js HTTP/1.1" 200 -
2022-08-13 18:51:31,516 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:31] "GET /js/123.1af480c9.js.map HTTP/1.1" 200 -
2022-08-13 18:51:33,756 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:33] "[36mGET /css/746.4039226c.css HTTP/1.1[0m" 304 -
2022-08-13 18:51:33,758 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:33] "[36mGET /js/746.d934ea50.js HTTP/1.1[0m" 304 -
2022-08-13 18:51:33,772 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:33] "GET /js/746.d934ea50.js.map HTTP/1.1" 200 -
2022-08-13 18:51:33,788 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:33] "GET /api/balance_pay HTTP/1.1" 200 -
2022-08-13 18:51:46,387 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 7212 and this is thread id 10060.
2022-08-13 18:51:46,388 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001E3F8F14B40>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 7212 and this is thread id 10060.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 7212 and this is thread id 10060.
2022-08-13 18:51:46,388 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 7472 and this is thread id 10060.
2022-08-13 18:51:46,388 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001E3F8F15740>
Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 7472 and this is thread id 10060.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 7472 and this is thread id 10060.
2022-08-13 18:51:46,389 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:46] "GET /api/basics HTTP/1.1" 200 -
2022-08-13 18:51:48,608 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:48] "GET /api/balance_pay HTTP/1.1" 200 -
2022-08-13 18:51:49,118 - INFO - 127.0.0.1 - - [13/Aug/2022 18:51:49] "GET /api/basics HTTP/1.1" 200 -
2022-08-14 02:32:35,816 - INFO - 127.0.0.1 - - [14/Aug/2022 02:32:35] "GET /api/balance_pay HTTP/1.1" 200 -
2022-08-14 02:33:28,363 - INFO - ¿ªÊ¼×ªÕË
2022-08-14 02:33:32,869 - INFO - Ç®°üÃû³Æ:13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV,Ç®°ü½ð¶î: 2.10226569
2022-08-14 02:33:32,870 - INFO - ¿ªÊ¼×ªÕË
2022-08-14 02:33:32,870 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/113uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  pay one  13HL77iS4Jy34X5dXmDQ4t53ZS5Ttzkei5qfuXqZpRxE1vh4PFU  2.06226569 --commit
2022-08-14 02:33:32,871 - INFO - ±¾´Î×ªÕË½ð¶î:2.06226569
2022-08-14 02:33:32,871 - INFO - Ç®°üÃû³Æ:13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV,Ç®°ü½ð¶î: 2.06226569
2022-08-14 02:33:33,819 - ERROR - Ç®°ü:13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV×ªÕËÊ§°Ü
2022-08-14 02:33:33,844 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "D:\wallet\OK4\pyhelm1\balance_pay.py", line 81, in banlance_pay
    amount = cmd_exec(addressPwd,key_path,wallet,dest_wallet,balanc)
  File "D:\wallet\OK4\pyhelm1\balance_pay.py", line 33, in cmd_exec
    jsonstr = resultJsonStr.split(']')[1] + "]}"
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 10940 and this is thread id 904.
2022-08-14 02:33:33,862 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001E3F8F15740>
Traceback (most recent call last):
  File "D:\wallet\OK4\pyhelm1\balance_pay.py", line 81, in banlance_pay
    amount = cmd_exec(addressPwd,key_path,wallet,dest_wallet,balanc)
  File "D:\wallet\OK4\pyhelm1\balance_pay.py", line 33, in cmd_exec
    jsonstr = resultJsonStr.split(']')[1] + "]}"
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 10940 and this is thread id 904.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 10940 and this is thread id 904.
2022-08-14 02:33:33,863 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "D:\wallet\OK4\pyhelm1\balance_pay.py", line 81, in banlance_pay
    amount = cmd_exec(addressPwd,key_path,wallet,dest_wallet,balanc)
  File "D:\wallet\OK4\pyhelm1\balance_pay.py", line 33, in cmd_exec
    jsonstr = resultJsonStr.split(']')[1] + "]}"
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13116 and this is thread id 904.
2022-08-14 02:33:33,863 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001E3F8F14B40>
Traceback (most recent call last):
  File "D:\wallet\OK4\pyhelm1\balance_pay.py", line 81, in banlance_pay
    amount = cmd_exec(addressPwd,key_path,wallet,dest_wallet,balanc)
  File "D:\wallet\OK4\pyhelm1\balance_pay.py", line 33, in cmd_exec
    jsonstr = resultJsonStr.split(']')[1] + "]}"
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13116 and this is thread id 904.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13116 and this is thread id 904.
2022-08-14 02:33:33,864 - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "D:\wallet\OK4\pyhelm1\balance_pay.py", line 81, in banlance_pay
    amount = cmd_exec(addressPwd,key_path,wallet,dest_wallet,balanc)
  File "D:\wallet\OK4\pyhelm1\balance_pay.py", line 33, in cmd_exec
    jsonstr = resultJsonStr.split(']')[1] + "]}"
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 17240 and this is thread id 904.
2022-08-14 02:33:33,865 - ERROR - Exception closing connection <sqlite3.Connection object at 0x000001E3F8F15840>
Traceback (most recent call last):
  File "D:\wallet\OK4\pyhelm1\balance_pay.py", line 81, in banlance_pay
    amount = cmd_exec(addressPwd,key_path,wallet,dest_wallet,balanc)
  File "D:\wallet\OK4\pyhelm1\balance_pay.py", line 33, in cmd_exec
    jsonstr = resultJsonStr.split(']')[1] + "]}"
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 682, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 17240 and this is thread id 904.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\pool\base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "C:\Users\90559\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 688, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 17240 and this is thread id 904.
2022-08-14 02:33:34,189 - INFO - 127.0.0.1 - - [14/Aug/2022 02:33:34] "POST /api/balance_pay HTTP/1.1" 200 -
2022-08-14 02:33:40,220 - INFO - 127.0.0.1 - - [14/Aug/2022 02:33:40] "GET /api/balance_pay HTTP/1.1" 200 -
2022-08-14 02:36:32,869 - INFO - ¿ªÊ¼×ªÕË
2022-08-14 02:37:01,259 - INFO - Ç®°üÃû³Æ:13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV,Ç®°ü½ð¶î: 2.10226569
2022-08-14 02:37:01,259 - INFO - ¿ªÊ¼×ªÕË
2022-08-14 02:37:01,260 - INFO - helium-wallet --format json -f D:/wallet/OK1/pythonProject/dataKey/113uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV.key  pay one  13HL77iS4Jy34X5dXmDQ4t53ZS5Ttzkei5qfuXqZpRxE1vh4PFU  2.06226569 --commit
2022-08-14 02:37:01,260 - INFO - ±¾´Î×ªÕË½ð¶î:2.06226569
2022-08-14 02:37:01,260 - INFO - Ç®°üÃû³Æ:13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV,Ç®°ü½ð¶î: 2.06226569
2022-08-14 02:37:02,033 - ERROR - Ç®°ü:13uAP1rPL3gm6UEJsnhhWTbcQAPapCVZvFQGtWSxLLfM11vhJUV×ªÕËÊ§°Ü
2022-08-14 02:37:02,398 - INFO - 127.0.0.1 - - [14/Aug/2022 02:37:02] "POST /api/balance_pay HTTP/1.1" 200 -
2022-08-14 02:37:09,161 - INFO - 127.0.0.1 - - [14/Aug/2022 02:37:09] "GET /api/balance_pay HTTP/1.1" 200 -
2022-08-17 11:09:07,202 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 11:12:24,632 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 11:13:14,770 - INFO - 127.0.0.1 - - [17/Aug/2022 11:13:14] "[31m[1mPOST /transfer HTTP/1.1[0m" 405 -
2022-08-17 11:13:26,449 - INFO - 127.0.0.1 - - [17/Aug/2022 11:13:26] "[31m[1mPOST /transfer HTTP/1.1[0m" 405 -
2022-08-17 11:14:43,379 - INFO - transfer
2022-08-17 11:14:43,379 - INFO - 123
2022-08-17 11:14:43,380 - INFO - 1
2022-08-17 11:14:43,380 - INFO - ['123']
2022-08-17 11:14:43,380 - INFO - 1,1,1,1,1,1
2022-08-17 11:14:43,380 - INFO - 127.0.0.1 - - [17/Aug/2022 11:14:43] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:15:13,298 - INFO - transfer
2022-08-17 11:15:13,298 - INFO - 1,1,1,1,1,1
2022-08-17 11:15:13,298 - INFO - 1
2022-08-17 11:15:13,298 - INFO - ['1', '1', '1', '1', '1', '1']
2022-08-17 11:15:13,298 - INFO - 123
2022-08-17 11:15:13,299 - INFO - 127.0.0.1 - - [17/Aug/2022 11:15:13] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:16:02,300 - INFO - transfer
2022-08-17 11:16:02,300 - INFO - 1,1,1,1,1,1
2022-08-17 11:16:02,300 - INFO - 1
2022-08-17 11:16:02,300 - INFO - ['1', '1', '1', '1', '1', '1']
2022-08-17 11:16:02,301 - INFO - 123
2022-08-17 11:16:02,301 - INFO - 127.0.0.1 - - [17/Aug/2022 11:16:02] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:16:26,483 - INFO - transfer
2022-08-17 11:16:26,483 - INFO - 1,1,1,1,1,1
2022-08-17 11:16:26,483 - INFO - 1
2022-08-17 11:16:26,483 - INFO - ['1', '1', '1', '1', '1', '1']
2022-08-17 11:16:26,483 - INFO - 123
2022-08-17 11:16:26,484 - INFO - 127.0.0.1 - - [17/Aug/2022 11:16:26] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:16:38,018 - INFO - transfer
2022-08-17 11:16:38,018 - INFO - 1,1,1,1,1,1
2022-08-17 11:16:38,019 - INFO - 1
2022-08-17 11:16:38,019 - INFO - ['1', '1', '1', '1', '1', '1']
2022-08-17 11:16:38,019 - INFO - 123
2022-08-17 11:16:38,019 - INFO - 127.0.0.1 - - [17/Aug/2022 11:16:38] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:16:51,306 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 11:16:53,854 - INFO - transfer
2022-08-17 11:16:53,854 - INFO - 1,1,1,1,1,1
2022-08-17 11:16:53,854 - INFO - 1
2022-08-17 11:16:53,854 - INFO - ['1', '1', '1', '1', '1', '1']
2022-08-17 11:16:53,854 - INFO - 123
2022-08-17 11:16:53,855 - INFO - 127.0.0.1 - - [17/Aug/2022 11:16:53] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:18:58,276 - INFO - ÁÐ³öÇ®°üµÄÈÈµãÊ§°Ü:Expecting value: line 1 column 1 (char 0)
2022-08-17 11:18:58,277 - INFO - 127.0.0.1 - - [17/Aug/2022 11:18:58] "[37mGET /api/transfer?wallet=123 HTTP/1.1[0m" 200 -
2022-08-17 11:19:02,065 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 11:19:03,260 - INFO - ÁÐ³öÇ®°üµÄÈÈµãÊ§°Ü:Expecting value: line 1 column 1 (char 0)
2022-08-17 11:19:03,261 - INFO - 127.0.0.1 - - [17/Aug/2022 11:19:03] "[37mGET /api/transfer?wallet=123 HTTP/1.1[0m" 200 -
2022-08-17 11:20:28,094 - INFO - ÁÐ³öÇ®°üµÄÈÈµãÊ§°Ü:Expecting value: line 1 column 1 (char 0)
2022-08-17 11:20:28,094 - INFO - 127.0.0.1 - - [17/Aug/2022 11:20:28] "[37mGET /api/transfer?wallet=123 HTTP/1.1[0m" 200 -
2022-08-17 11:20:29,775 - INFO - ÁÐ³öÇ®°üµÄÈÈµãÊ§°Ü:Expecting value: line 1 column 1 (char 0)
2022-08-17 11:20:29,775 - INFO - 127.0.0.1 - - [17/Aug/2022 11:20:29] "[37mGET /api/transfer?wallet=123 HTTP/1.1[0m" 200 -
2022-08-17 11:20:34,309 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 11:20:37,434 - INFO - 127.0.0.1 - - [17/Aug/2022 11:20:37] "[37mGET /api/transfer?wallet=123 HTTP/1.1[0m" 200 -
2022-08-17 11:20:38,162 - INFO - 127.0.0.1 - - [17/Aug/2022 11:20:38] "[37mGET /api/transfer?wallet=123 HTTP/1.1[0m" 200 -
2022-08-17 11:21:03,690 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 11:21:04,875 - INFO - 127.0.0.1 - - [17/Aug/2022 11:21:04] "[37mGET /api/transfer?wallet=123 HTTP/1.1[0m" 200 -
2022-08-17 11:21:05,914 - INFO - 127.0.0.1 - - [17/Aug/2022 11:21:05] "[37mGET /api/transfer?wallet=123 HTTP/1.1[0m" 200 -
2022-08-17 11:21:07,338 - INFO - 127.0.0.1 - - [17/Aug/2022 11:21:07] "[37mGET /api/transfer?wallet= HTTP/1.1[0m" 200 -
2022-08-17 11:21:07,835 - INFO - 127.0.0.1 - - [17/Aug/2022 11:21:07] "[37mGET /api/transfer?wallet= HTTP/1.1[0m" 200 -
2022-08-17 11:21:09,860 - INFO - 127.0.0.1 - - [17/Aug/2022 11:21:09] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:21:10,410 - INFO - 127.0.0.1 - - [17/Aug/2022 11:21:10] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:21:11,938 - INFO - 127.0.0.1 - - [17/Aug/2022 11:21:11] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:21:12,474 - INFO - 127.0.0.1 - - [17/Aug/2022 11:21:12] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:21:13,306 - INFO - 127.0.0.1 - - [17/Aug/2022 11:21:13] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:21:13,865 - INFO - 127.0.0.1 - - [17/Aug/2022 11:21:13] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:22:27,185 - INFO - 127.0.0.1 - - [17/Aug/2022 11:22:27] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:24:12,307 - INFO - transfer
2022-08-17 11:24:12,308 - INFO - 1,1,1,
2022-08-17 11:24:12,308 - INFO - 
2022-08-17 11:24:12,308 - INFO - 12
2022-08-17 11:24:12,308 - INFO - ['1', '1', '1', '']
2022-08-17 11:24:12,308 - INFO - 123
2022-08-17 11:24:12,308 - INFO - 127.0.0.1 - - [17/Aug/2022 11:24:12] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:24:31,226 - INFO - 127.0.0.1 - - [17/Aug/2022 11:24:31] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:24:32,115 - INFO - 127.0.0.1 - - [17/Aug/2022 11:24:32] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:25:15,691 - INFO - 127.0.0.1 - - [17/Aug/2022 11:25:15] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:25:23,797 - INFO - 127.0.0.1 - - [17/Aug/2022 11:25:23] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:25:43,273 - INFO - transfer
2022-08-17 11:25:43,273 - INFO - 1,1,1
2022-08-17 11:25:43,273 - INFO - 
2022-08-17 11:25:43,273 - INFO - 123
2022-08-17 11:25:43,273 - INFO - ['1', '1', '1']
2022-08-17 11:25:43,273 - INFO - 123
2022-08-17 11:25:43,274 - INFO - 127.0.0.1 - - [17/Aug/2022 11:25:43] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:25:59,146 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 11:26:01,707 - INFO - 127.0.0.1 - - [17/Aug/2022 11:26:01] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:47:17,555 - INFO - 127.0.0.1 - - [17/Aug/2022 11:47:17] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:47:32,513 - INFO - transfer
2022-08-17 11:47:32,513 - INFO - eqwe,qeqeqeq123132
2022-08-17 11:47:32,513 - INFO - 
2022-08-17 11:47:32,513 - INFO - 123
2022-08-17 11:47:32,513 - INFO - ['eqwe', 'qeqeqeq123132']
2022-08-17 11:47:32,513 - INFO - 1234
2022-08-17 11:47:32,514 - INFO - 127.0.0.1 - - [17/Aug/2022 11:47:32] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:49:19,122 - INFO - 127.0.0.1 - - [17/Aug/2022 11:49:19] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:49:33,282 - INFO - transfer
2022-08-17 11:49:33,282 - INFO - eqwe,qeqeqeq
2022-08-17 11:49:33,282 - INFO - 
2022-08-17 11:49:33,282 - INFO - 12
2022-08-17 11:49:33,282 - INFO - ['eqwe', 'qeqeqeq']
2022-08-17 11:49:33,282 - INFO - 123132
2022-08-17 11:49:33,283 - INFO - 127.0.0.1 - - [17/Aug/2022 11:49:33] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:51:19,755 - INFO - 127.0.0.1 - - [17/Aug/2022 11:51:19] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 11:52:14,438 - INFO - 127.0.0.1 - - [17/Aug/2022 11:52:14] "[33mGET /balance_pay HTTP/1.1[0m" 404 -
2022-08-17 11:52:15,221 - INFO - 127.0.0.1 - - [17/Aug/2022 11:52:15] "[33mGET /basics HTTP/1.1[0m" 404 -
2022-08-17 12:22:45,809 - INFO - 127.0.0.1 - - [17/Aug/2022 12:22:45] "[33mGET /basics HTTP/1.1[0m" 404 -
2022-08-17 12:22:47,273 - INFO - 127.0.0.1 - - [17/Aug/2022 12:22:47] "[33mGET /balance_pay HTTP/1.1[0m" 404 -
2022-08-17 12:22:50,201 - INFO - 127.0.0.1 - - [17/Aug/2022 12:22:50] "[33mGET /basics HTTP/1.1[0m" 404 -
2022-08-17 12:23:24,459 - INFO - 127.0.0.1 - - [17/Aug/2022 12:23:24] "[33mGET /basics HTTP/1.1[0m" 404 -
2022-08-17 12:23:25,554 - INFO - 127.0.0.1 - - [17/Aug/2022 12:23:25] "[33mGET /balance_pay HTTP/1.1[0m" 404 -
2022-08-17 12:23:26,967 - INFO - 127.0.0.1 - - [17/Aug/2022 12:23:26] "[33mGET /balance_pay HTTP/1.1[0m" 404 -
2022-08-17 12:23:51,767 - INFO - 127.0.0.1 - - [17/Aug/2022 12:23:51] "[33mGET /basics HTTP/1.1[0m" 404 -
2022-08-17 12:24:00,283 - INFO - 127.0.0.1 - - [17/Aug/2022 12:24:00] "[33mGET /basics HTTP/1.1[0m" 404 -
2022-08-17 12:24:01,179 - INFO - 127.0.0.1 - - [17/Aug/2022 12:24:01] "[33mGET /balance_pay HTTP/1.1[0m" 404 -
2022-08-17 12:24:02,323 - INFO - 127.0.0.1 - - [17/Aug/2022 12:24:02] "[33mGET /basics HTTP/1.1[0m" 404 -
2022-08-17 12:24:19,064 - INFO - 127.0.0.1 - - [17/Aug/2022 12:24:19] "[33mGET /balance_pay HTTP/1.1[0m" 404 -
2022-08-17 12:24:25,255 - INFO - 127.0.0.1 - - [17/Aug/2022 12:24:25] "[37mGET /api/transfer?wallet=1 HTTP/1.1[0m" 200 -
2022-08-17 14:09:37,700 - INFO - 127.0.0.1 - - [17/Aug/2022 14:09:37] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:13:27,201 - INFO - 127.0.0.1 - - [17/Aug/2022 14:13:27] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:17:26,315 - INFO - 127.0.0.1 - - [17/Aug/2022 14:17:26] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:22:36,090 - INFO - 127.0.0.1 - - [17/Aug/2022 14:22:36] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:22:47,437 - INFO - 127.0.0.1 - - [17/Aug/2022 14:22:47] "[33mGET /balance_pay HTTP/1.1[0m" 404 -
2022-08-17 14:22:55,566 - INFO - 127.0.0.1 - - [17/Aug/2022 14:22:55] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:26:30,239 - INFO - 127.0.0.1 - - [17/Aug/2022 14:26:30] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:26:32,839 - INFO - 127.0.0.1 - - [17/Aug/2022 14:26:32] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:26:33,261 - INFO - 127.0.0.1 - - [17/Aug/2022 14:26:33] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:28:43,502 - INFO - 127.0.0.1 - - [17/Aug/2022 14:28:43] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:34:54,567 - INFO - 127.0.0.1 - - [17/Aug/2022 14:34:54] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:35:41,243 - INFO - 127.0.0.1 - - [17/Aug/2022 14:35:41] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:44:48,541 - INFO - 127.0.0.1 - - [17/Aug/2022 14:44:48] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:52:30,465 - INFO - 127.0.0.1 - - [17/Aug/2022 14:52:30] "[37mGET /api/basics HTTP/1.1[0m" 200 -
2022-08-17 14:52:39,679 - INFO - 127.0.0.1 - - [17/Aug/2022 14:52:39] "[35m[1mGET /api/balance_pay HTTP/1.1[0m" 500 -
2022-08-17 14:54:28,338 - INFO - 127.0.0.1 - - [17/Aug/2022 14:54:28] "[35m[1mGET /api/balance_pay HTTP/1.1[0m" 500 -
2022-08-17 14:54:44,772 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 14:54:48,812 - INFO - 127.0.0.1 - - [17/Aug/2022 14:54:48] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:54:49,451 - INFO - 127.0.0.1 - - [17/Aug/2022 14:54:49] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:54:49,939 - INFO - 127.0.0.1 - - [17/Aug/2022 14:54:49] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:55:48,030 - INFO - 127.0.0.1 - - [17/Aug/2022 14:55:48] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:56:41,397 - INFO - 127.0.0.1 - - [17/Aug/2022 14:56:41] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:56:42,531 - INFO - 127.0.0.1 - - [17/Aug/2022 14:56:42] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:56:43,003 - INFO - 127.0.0.1 - - [17/Aug/2022 14:56:43] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:56:43,890 - INFO - 127.0.0.1 - - [17/Aug/2022 14:56:43] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:56:44,397 - INFO - 127.0.0.1 - - [17/Aug/2022 14:56:44] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 14:57:06,553 - INFO - 127.0.0.1 - - [17/Aug/2022 14:57:06] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 14:57:09,021 - INFO - 127.0.0.1 - - [17/Aug/2022 14:57:09] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 14:57:10,800 - INFO - 127.0.0.1 - - [17/Aug/2022 14:57:10] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:08:45,260 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 15:08:49,831 - INFO - 127.0.0.1 - - [17/Aug/2022 15:08:49] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:08:50,702 - INFO - 127.0.0.1 - - [17/Aug/2022 15:08:50] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:08:51,565 - INFO - 127.0.0.1 - - [17/Aug/2022 15:08:51] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:09:00,854 - INFO - 127.0.0.1 - - [17/Aug/2022 15:09:00] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:10:13,885 - INFO - 127.0.0.1 - - [17/Aug/2022 15:10:13] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:10:14,532 - INFO - 127.0.0.1 - - [17/Aug/2022 15:10:14] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:12:24,277 - INFO - 127.0.0.1 - - [17/Aug/2022 15:12:24] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:12:25,332 - INFO - 127.0.0.1 - - [17/Aug/2022 15:12:25] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:12:26,158 - INFO - 127.0.0.1 - - [17/Aug/2022 15:12:26] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:12:59,172 - INFO - 127.0.0.1 - - [17/Aug/2022 15:12:59] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 15:15:05,110 - INFO - 127.0.0.1 - - [17/Aug/2022 15:15:05] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:15:05,813 - INFO - 127.0.0.1 - - [17/Aug/2022 15:15:05] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:15:06,309 - INFO - 127.0.0.1 - - [17/Aug/2022 15:15:06] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:15:13,549 - INFO - 127.0.0.1 - - [17/Aug/2022 15:15:13] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:15:14,235 - INFO - 127.0.0.1 - - [17/Aug/2022 15:15:14] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:15:14,852 - INFO - 127.0.0.1 - - [17/Aug/2022 15:15:14] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:15:20,293 - INFO - 127.0.0.1 - - [17/Aug/2022 15:15:20] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:15:20,830 - INFO - 127.0.0.1 - - [17/Aug/2022 15:15:20] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:15:21,412 - INFO - 127.0.0.1 - - [17/Aug/2022 15:15:21] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:15:39,183 - INFO - 127.0.0.1 - - [17/Aug/2022 15:15:39] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:15:39,817 - INFO - 127.0.0.1 - - [17/Aug/2022 15:15:39] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:16:02,989 - INFO - 127.0.0.1 - - [17/Aug/2022 15:16:02] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:16:03,500 - INFO - 127.0.0.1 - - [17/Aug/2022 15:16:03] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:16:04,012 - INFO - 127.0.0.1 - - [17/Aug/2022 15:16:04] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:18:30,145 - INFO - 127.0.0.1 - - [17/Aug/2022 15:18:30] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 15:18:37,167 - INFO - 127.0.0.1 - - [17/Aug/2022 15:18:37] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 15:18:55,382 - INFO - transfer
2022-08-17 15:18:55,382 - INFO - 1
2022-08-17 15:18:55,383 - INFO - 
2022-08-17 15:18:55,383 - INFO - 123
2022-08-17 15:18:55,383 - INFO - ['1']
2022-08-17 15:18:55,383 - INFO - 123
2022-08-17 15:18:55,383 - INFO - 127.0.0.1 - - [17/Aug/2022 15:18:55] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 15:19:28,443 - INFO - 127.0.0.1 - - [17/Aug/2022 15:19:28] "[37mGET /api/transfer?wallet=123 HTTP/1.1[0m" 200 -
2022-08-17 15:19:39,432 - INFO - transfer
2022-08-17 15:19:39,432 - INFO - eqwe,qeqeqeq
2022-08-17 15:19:39,433 - INFO - 
2022-08-17 15:19:39,433 - INFO - 12
2022-08-17 15:19:39,433 - INFO - ['eqwe', 'qeqeqeq']
2022-08-17 15:19:39,433 - INFO - 123
2022-08-17 15:19:39,433 - INFO - 127.0.0.1 - - [17/Aug/2022 15:19:39] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 15:20:15,951 - INFO - 127.0.0.1 - - [17/Aug/2022 15:20:15] "[33mGET /transfer?wallet=123 HTTP/1.1[0m" 404 -
2022-08-17 15:20:16,718 - INFO - 127.0.0.1 - - [17/Aug/2022 15:20:16] "[33mGET /transfer?wallet=123 HTTP/1.1[0m" 404 -
2022-08-17 15:20:17,348 - INFO - 127.0.0.1 - - [17/Aug/2022 15:20:17] "[33mGET /transfer?wallet=123 HTTP/1.1[0m" 404 -
2022-08-17 15:20:18,267 - INFO - 127.0.0.1 - - [17/Aug/2022 15:20:18] "[33mGET /transfer?wallet=123 HTTP/1.1[0m" 404 -
2022-08-17 15:20:19,060 - INFO - 127.0.0.1 - - [17/Aug/2022 15:20:19] "[33mGET /transfer?wallet=123 HTTP/1.1[0m" 404 -
2022-08-17 15:20:19,749 - INFO - 127.0.0.1 - - [17/Aug/2022 15:20:19] "[33mGET /transfer?wallet=123 HTTP/1.1[0m" 404 -
2022-08-17 15:20:20,323 - INFO - 127.0.0.1 - - [17/Aug/2022 15:20:20] "[33mGET /transfer?wallet=123 HTTP/1.1[0m" 404 -
2022-08-17 15:20:20,789 - INFO - 127.0.0.1 - - [17/Aug/2022 15:20:20] "[33mGET /transfer?wallet=123 HTTP/1.1[0m" 404 -
2022-08-17 15:20:21,246 - INFO - 127.0.0.1 - - [17/Aug/2022 15:20:21] "[33mGET /transfer?wallet=123 HTTP/1.1[0m" 404 -
2022-08-17 15:20:21,900 - INFO - 127.0.0.1 - - [17/Aug/2022 15:20:21] "[33mGET /transfer?wallet=123 HTTP/1.1[0m" 404 -
2022-08-17 15:21:39,666 - INFO - 127.0.0.1 - - [17/Aug/2022 15:21:39] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 15:24:31,985 - INFO - 127.0.0.1 - - [17/Aug/2022 15:24:31] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:24:32,975 - INFO - 127.0.0.1 - - [17/Aug/2022 15:24:32] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:24:33,779 - INFO - 127.0.0.1 - - [17/Aug/2022 15:24:33] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:24:34,428 - INFO - 127.0.0.1 - - [17/Aug/2022 15:24:34] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:24:34,908 - INFO - 127.0.0.1 - - [17/Aug/2022 15:24:34] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 15:24:35,532 - INFO - 127.0.0.1 - - [17/Aug/2022 15:24:35] "[33mGET /transfer HTTP/1.1[0m" 404 -
2022-08-17 16:07:13,125 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 16:07:24,939 - INFO - 127.0.0.1 - - [17/Aug/2022 16:07:24] "[37mGET /api/basics HTTP/1.1[0m" 200 -
2022-08-17 16:07:30,489 - INFO - 127.0.0.1 - - [17/Aug/2022 16:07:30] "[37mGET /api/basics HTTP/1.1[0m" 200 -
2022-08-17 16:07:35,483 - INFO - 127.0.0.1 - - [17/Aug/2022 16:07:35] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 16:09:20,907 - INFO - 127.0.0.1 - - [17/Aug/2022 16:09:20] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 16:09:28,129 - INFO - 127.0.0.1 - - [17/Aug/2022 16:09:28] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 16:10:55,440 - INFO - 127.0.0.1 - - [17/Aug/2022 16:10:55] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 16:11:30,070 - INFO - 127.0.0.1 - - [17/Aug/2022 16:11:30] "[37mGET /api/basics HTTP/1.1[0m" 200 -
2022-08-17 16:13:54,300 - INFO - 127.0.0.1 - - [17/Aug/2022 16:13:54] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 16:15:29,941 - INFO - transfer
2022-08-17 16:15:29,941 - INFO - 132132
2022-08-17 16:15:29,941 - INFO - 
2022-08-17 16:15:29,941 - INFO - 12
2022-08-17 16:15:29,941 - INFO - ['132132']
2022-08-17 16:15:29,941 - INFO - 123132
2022-08-17 16:15:29,942 - INFO - 127.0.0.1 - - [17/Aug/2022 16:15:29] "[37mPOST /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 16:15:59,139 - INFO - 127.0.0.1 - - [17/Aug/2022 16:15:59] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 16:16:02,529 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 16:16:04,898 - INFO - ÁÐ³öÇ®°üµÄÈÈµãÊ§°Ü:Expecting value: line 1 column 1 (char 0)
2022-08-17 16:16:04,898 - INFO - 127.0.0.1 - - [17/Aug/2022 16:16:04] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 16:16:15,976 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 16:16:39,906 - INFO - ÁÐ³öÇ®°üµÄÈÈµãÊ§°Ü:Expecting value: line 1 column 1 (char 0)
2022-08-17 16:16:39,906 - INFO - 127.0.0.1 - - [17/Aug/2022 16:16:39] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 16:17:57,109 - INFO - 127.0.0.1 - - [17/Aug/2022 16:17:57] "[37mGET /api/basics HTTP/1.1[0m" 200 -
2022-08-17 16:20:17,324 - INFO - 127.0.0.1 - - [17/Aug/2022 16:20:17] "[35m[1mGET /api/balance_pay HTTP/1.1[0m" 500 -
2022-08-17 16:20:48,228 - INFO - 127.0.0.1 - - [17/Aug/2022 16:20:48] "[35m[1mGET /api/balance_pay HTTP/1.1[0m" 500 -
2022-08-17 16:20:48,258 - INFO - 127.0.0.1 - - [17/Aug/2022 16:20:48] "[35m[1mGET /api/balance_pay HTTP/1.1[0m" 500 -
2022-08-17 17:56:36,532 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 17:57:23,531 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 17:58:05,260 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 18:00:42,990 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 18:01:00,417 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 18:35:24,089 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 18:37:19,608 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 18:38:10,653 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:10] "[33mGET /basics HTTP/1.1[0m" 404 -
2022-08-17 18:38:13,387 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:13] "[37mGET / HTTP/1.1[0m" 200 -
2022-08-17 18:38:13,895 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:13] "[37mGET /js/chunk-vendors.79915abe.js HTTP/1.1[0m" 200 -
2022-08-17 18:38:13,895 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:13] "[37mGET /css/chunk-vendors.0b0c58b7.css HTTP/1.1[0m" 200 -
2022-08-17 18:38:13,895 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:13] "[37mGET /css/app.fe3c3b3a.css HTTP/1.1[0m" 200 -
2022-08-17 18:38:13,895 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:13] "[37mGET /js/app.dd7f32ec.js HTTP/1.1[0m" 200 -
2022-08-17 18:38:14,025 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:14] "[37mGET /js/chunk-vendors.79915abe.js.map HTTP/1.1[0m" 200 -
2022-08-17 18:38:14,026 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:14] "[37mGET /js/app.dd7f32ec.js.map HTTP/1.1[0m" 200 -
2022-08-17 18:38:14,034 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:14] "[37mGET /fonts/element-icons.ff18efd1.woff HTTP/1.1[0m" 200 -
2022-08-17 18:38:14,035 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:14] "[37mGET /api/basics HTTP/1.1[0m" 200 -
2022-08-17 18:38:25,393 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:25] "[37mGET /css/270.84d4acab.css HTTP/1.1[0m" 200 -
2022-08-17 18:38:25,394 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:25] "[37mGET /js/270.b85dbd8d.js HTTP/1.1[0m" 200 -
2022-08-17 18:38:35,487 - INFO - ÁÐ³öÇ®°üµÄÈÈµãÊ§°Ü:Expecting value: line 1 column 1 (char 0)
2022-08-17 18:38:35,488 - INFO - 127.0.0.1 - - [17/Aug/2022 18:38:35] "[37mGET /api/transfer HTTP/1.1[0m" 200 -
2022-08-17 18:43:33,153 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-08-17 18:43:35,513 - INFO - 127.0.0.1 - - [17/Aug/2022 18:43:35] "[33mGET /hotspot HTTP/1.1[0m" 404 -
2022-08-17 18:43:38,199 - INFO - 127.0.0.1 - - [17/Aug/2022 18:43:38] "[37mGET / HTTP/1.1[0m" 200 -
2022-08-17 18:43:38,350 - INFO - 127.0.0.1 - - [17/Aug/2022 18:43:38] "[37mGET /api/basics HTTP/1.1[0m" 200 -
2022-08-17 18:43:51,922 - INFO - transfer
2022-08-17 18:43:51,923 - INFO - 
2022-08-17 18:43:51,923 - INFO - 12
2022-08-17 18:43:51,923 - INFO - ['123', '123']
2022-08-17 18:43:51,923 - INFO - 123
2022-08-17 18:43:51,937 - INFO - 127.0.0.1 - - [17/Aug/2022 18:43:51] "[35m[1mPOST /api/transfer HTTP/1.1[0m" 500 -
